(function(c,t,k,z){function s(a){for(;a&&"undefined"!==typeof a.originalEvent;)a=a.originalEvent;return a}function F(a){for(var n={},e,f;a;){e=c.data(a,I);for(f in e)e[f]&&(n[f]=n.hasVirtualBinding=!0);a=a.parentNode}return n}function G(){E&&(clearTimeout(E),E=0);E=setTimeout(function(){J=E=0;m.length=0;K=!1;D=!0},c.vmouse.resetTimerDuration)}function p(a,n,e){var f,q;if(!(q=e&&e[a])){if(e=!e)a:{for(e=n.target;e;){if((q=c.data(e,I))&&(!a||q[a]))break a;e=e.parentNode}e=null}q=e}if(q){f=n;e=f.type;
var w,O;f=c.Event(f);f.type=a;a=f.originalEvent;q=c.event.props;-1<e.search(/^(mouse|click)/)&&(q=Q);if(a)for(O=q.length,w;O;)w=q[--O],f[w]=a[w];-1<e.search(/mouse(down|up)|click/)&&!f.which&&(f.which=1);if(-1!==e.search(/^touch/)&&(w=s(a),e=w.touches,w=w.changedTouches,a=e&&e.length?e[0]:w&&w.length?w[0]:z))for(e=0,q=g.length;e<q;e++)w=g[e],f[w]=a[w];c(n.target).trigger(f)}return f}function A(a){var n=c.data(a.target,L);K||J&&J===n||!(n=p("v"+a.type,a))||(n.isDefaultPrevented()&&a.preventDefault(),
n.isPropagationStopped()&&a.stopPropagation(),n.isImmediatePropagationStopped()&&a.stopImmediatePropagation())}function a(a){var n=s(a).touches,e;n&&1===n.length&&(e=a.target,n=F(e),n.hasVirtualBinding&&(J=x++,c.data(e,L,J),E&&(clearTimeout(E),E=0),H=D=!1,e=s(a).touches[0],B=e.pageX,M=e.pageY,p("vmouseover",a,n),p("vmousedown",a,n)))}function b(a){D||(H||p("vmousecancel",a,F(a.target)),H=!0,G())}function d(a){if(!D){var n=s(a).touches[0],e=H,f=c.vmouse.moveDistanceThreshold,q=F(a.target);(H=H||Math.abs(n.pageX-
B)>f||Math.abs(n.pageY-M)>f)&&!e&&p("vmousecancel",a,q);p("vmousemove",a,q);G()}}function v(a){if(!D){D=!0;var n=F(a.target),e;p("vmouseup",a,n);!H&&((e=p("vclick",a,n))&&e.isDefaultPrevented())&&(e=s(a).changedTouches[0],m.push({touchID:J,x:e.clientX,y:e.clientY}),K=!0);p("vmouseout",a,n);H=!1;G()}}function h(a){a=c.data(a,I);var n;if(a)for(n in a)if(a[n])return!0;return!1}function N(){}function C(g){var n=g.substr(1);return{setup:function(){h(this)||c.data(this,I,{});c.data(this,I)[g]=!0;u[g]=(u[g]||
0)+1;1===u[g]&&r.bind(n,A);c(this).bind(n,N);y&&(u.touchstart=(u.touchstart||0)+1,1===u.touchstart&&r.bind("touchstart",a).bind("touchend",v).bind("touchmove",d).bind("scroll",b))},teardown:function(){--u[g];u[g]||r.unbind(n,A);y&&(--u.touchstart,u.touchstart||r.unbind("touchstart",a).unbind("touchmove",d).unbind("touchend",v).unbind("scroll",b));var e=c(this),f=c.data(this,I);f&&(f[g]=!1);e.unbind(n,N);h(this)||e.removeData(I)}}}var I="virtualMouseBindings",L="virtualTouchID";t="vmouseover vmousedown vmousemove vmouseup vclick vmouseout vmousecancel".split(" ");
var g="clientX clientY pageX pageY screenX screenY".split(" "),Q=c.event.props.concat(c.event.mouseHooks?c.event.mouseHooks.props:[]),u={},E=0,B=0,M=0,H=!1,m=[],K=!1,D=!1,y="addEventListener"in k,r=c(k),x=1,J=0,l;c.vmouse={moveDistanceThreshold:10,clickDistanceThreshold:10,resetTimerDuration:1500};for(var P=0;P<t.length;P++)c.event.special[t[P]]=C(t[P]);y&&k.addEventListener("click",function(a){var n=m.length,e=a.target,f,q,w,O,g;if(n)for(f=a.clientX,q=a.clientY,l=c.vmouse.clickDistanceThreshold,
w=e;w;){for(O=0;O<n;O++)if(g=m[O],w===e&&Math.abs(g.x-f)<l&&Math.abs(g.y-q)<l||c.data(w,L)===g.touchID){a.preventDefault();a.stopPropagation();return}w=w.parentNode}},!0)})(jQuery,window,document);
!function(c,t,k){function z(a,b){var g=t.createElement(a||"div"),d;for(d in b)g[d]=b[d];return g}function s(a){for(var b=1,g=arguments.length;b<g;b++)a.appendChild(arguments[b]);return a}function F(a,b,g,c){var u=["opacity",b,~~(100*a),g,c].join("-");g=0.01+100*(g/c);c=Math.max(1-(1-a)/b*(100-g),a);var k=v.substring(0,v.indexOf("Animation")).toLowerCase();d[u]||(h.insertRule("@"+(k&&"-"+k+"-"||"")+"keyframes "+u+"{0%{opacity:"+c+"}"+g+"%{opacity:"+a+"}"+(g+0.01)+"%{opacity:1}"+(g+b)%100+"%{opacity:"+
a+"}100%{opacity:"+c+"}}",h.cssRules.length),d[u]=1);return u}function G(a,d){var g=a.style,c,u;if(g[d]!==k)return d;d=d.charAt(0).toUpperCase()+d.slice(1);for(u=0;u<b.length;u++)if(c=b[u]+d,g[c]!==k)return c}function p(a,b){for(var g in b)a.style[G(a,g)||g]=b[g];return a}function A(a){for(var b=1;b<arguments.length;b++){var g=arguments[b],d;for(d in g)a[d]===k&&(a[d]=g[d])}return a}function a(a){for(var b={x:a.offsetLeft,y:a.offsetTop};a=a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop;return b}
var b=["webkit","Moz","ms","O"],d={},v,h=function(){var a=z("style",{type:"text/css"});s(t.getElementsByTagName("head")[0],a);return a.sheet||a.styleSheet}(),N={lines:12,length:7,width:5,radius:10,rotate:0,corners:1,color:"#000",speed:1,trail:100,opacity:0.25,fps:20,zIndex:2E9,className:"spinner",top:"auto",left:"auto",position:"relative"},C=function L(a){if(!this.spin)return new L(a);this.opts=A(a||{},L.defaults,N)};C.defaults={};A(C.prototype,{spin:function(b){this.stop();var g=this,d=g.opts,c=
g.el=p(z(0,{className:d.className}),{position:d.position,width:0,zIndex:d.zIndex}),h=d.radius+d.length+d.width,k,s;b&&(b.insertBefore(c,b.firstChild||null),s=a(b),k=a(c),p(c,{left:("auto"==d.left?s.x-k.x+(b.offsetWidth>>1):parseInt(d.left,10)+h)+"px",top:("auto"==d.top?s.y-k.y+(b.offsetHeight>>1):parseInt(d.top,10)+h)+"px"}));c.setAttribute("aria-role","progressbar");g.lines(c,g.opts);if(!v){var t=0,m=d.fps,C=m/d.speed,N=(1-d.opacity)/(C*d.trail/100),y=C/d.lines;(function x(){t++;for(var a=d.lines;a;a--){var b=
Math.max(1-(t+a*y)%C*N,d.opacity);g.opacity(c,d.lines-a,b,d)}g.timeout=g.el&&setTimeout(x,~~(1E3/m))})()}return g},stop:function(){var a=this.el;a&&(clearTimeout(this.timeout),a.parentNode&&a.parentNode.removeChild(a),this.el=k);return this},lines:function(a,b){function d(a,v){return p(z(),{position:"absolute",width:b.length+b.width+"px",height:b.width+"px",background:a,boxShadow:v,transformOrigin:"left",transform:"rotate("+~~(360/b.lines*c+b.rotate)+"deg) translate("+b.radius+"px,0)",borderRadius:(b.corners*
b.width>>1)+"px"})}for(var c=0,h;c<b.lines;c++)h=p(z(),{position:"absolute",top:1+~(b.width/2)+"px",transform:b.hwaccel?"translate3d(0,0,0)":"",opacity:b.opacity,animation:v&&F(b.opacity,b.trail,c,b.lines)+" "+1/b.speed+"s linear infinite"}),b.shadow&&s(h,p(d("#000","0 0 4px #000"),{top:"2px"})),s(a,s(h,d(b.color,"0 0 1px rgba(0,0,0,.1)")));return a},opacity:function(a,b,d){b<a.childNodes.length&&(a.childNodes[b].style.opacity=d)}});(function(){function a(b,d){return z("<"+b+' xmlns="urn:schemas-microsoft.com:vml" class="spin-vml">',
d)}var b=p(z("group"),{behavior:"url(#default#VML)"});!G(b,"transform")&&b.adj?(h.addRule(".spin-vml","behavior:url(#default#VML)"),C.prototype.lines=function(b,d){function c(){return p(a("group",{coordsize:h+" "+h,coordorigin:-v+" "+-v}),{width:h,height:h})}function g(b,h,m){s(k,s(p(c(),{rotation:360/d.lines*b+"deg",left:~~h}),s(p(a("roundrect",{arcsize:d.corners}),{width:v,height:d.width,left:d.radius,top:-d.width>>1,filter:m}),a("fill",{color:d.color,opacity:d.opacity}),a("stroke",{opacity:0}))))}
var v=d.length+d.width,h=2*v,m=2*-(d.width+d.length)+"px",k=p(c(),{position:"absolute",top:m,left:m});if(d.shadow)for(m=1;m<=d.lines;m++)g(m,-2,"progid:DXImageTransform.Microsoft.Blur(pixelradius=2,makeshadow=1,shadowopacity=.3)");for(m=1;m<=d.lines;m++)g(m);return s(b,k)},C.prototype.opacity=function(a,b,d,c){a=a.firstChild;c=c.shadow&&c.lines||0;a&&b+c<a.childNodes.length&&(a=(a=(a=a.childNodes[b+c])&&a.firstChild)&&a.firstChild)&&(a.opacity=d)}):v=G(b,"animation")})();"function"==typeof define&&
define.amd?define(function(){return C}):c.Spinner=C}(window,document);$.fn.spin=function(c){this.each(function(){var t=$(this),k=t.data();k.spinner&&(k.spinner.stop(),delete k.spinner);!1!==c&&(k.spinner=(new Spinner($.extend({color:t.css("color")},c))).spin(this))});return this};
(function(c,t){function k(a){return 4>a.length?a:k(a.substr(0,a.length-3))+","+a.substr(a.length-3)}function z(a){a=a||c.event;a.stopPropagation&&a.stopPropagation();a.preventDefault&&a.preventDefault();a.cancelBubble=!0;a.cancel=!0;return a.returnValue=!1}function s(a){function b(){var a=$(this),b=a.parent(),a=a.find("option:selected").attr("selected",!0).text(),a=b.find(".val").text(a);b.is(":visible")&&b.hasClass("fancy-select-resize")&&b.width(a.outerWidth())}$(a||".fancy-select-container select").change(b).each(b)}
function F(a){return(a+"").replace(/&/g,"-And-").replace(/[^\w]/g,"-").replace(/-{2,}/g,"-").replace(/^-|-$/g,"")}function G(a){var b=$(this);b.parent().find(".noshow").toggle();var d=$(this).text();-1!==d.search("More")?b.text(d.replace("More","Less")):b.text(d.replace("Less","More"));z(a)}t.domain=FTB.tld;Array.indexOf||(Array.prototype.indexOf=function(a,b){for(var d=b||0;d<this.length;d++)if(this[d]==a)return d;return-1});c.console||(c.console={});c.console.log||(c.console.log=function(){});c.is_mobile=
/iphone|ipad|ipod|android|blackberry|mini|windows\sce|palm/i.test(navigator.userAgent.toLowerCase());c.is_touch=!!("ontouchstart"in c)||!!navigator.msMaxTouchPoints;c.use_svg=t.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Shape","1.1");c.$&&(void 0===$.fn.quickEach&&($.fn.quickEach=function(){var a=jQuery([1]);return function(b){var d=-1,c,h=this.length;try{for(;++d<h&&(c=a[0]=this[d])&&!1!==b.call(a,d,c););}catch(k){throw delete a[0],k;}delete a[0];return this}}()),$.fn.showIf=function(a){return this[a?
"show":"hide"]()},$.fn.classIf=function(a,b){return this[(b?"add":"remove")+"Class"](a)});var p=1,A={};c.sxCheckbox=function(a){a=""+('<div class="sx-cb'+(a?" on":"")+'">');a=use_svg?a+'<svg class="sx-cb-svg" width="31" height="31"><path fill="none" stroke-width="3" d="M 9 13 L 15 19 L 25 7"/></svg>':a+'<div class="sx-cb-inner"><div class="sx-cb-mark"></div><div class="sx-cb1"></div><div class="sx-cb2"></div><div class="sx-cb3"></div></div>';return a+"</div>"};FTB.setUpStars=function(){var a,b="";
for(a=1;6>a;a+=1)b+="<span data-star='"+a+"' class='star'><span class='star-icon'></span><span class='tl'></span><span class='tr'></span><span class='bl'></span><span class='br'></span></span>",5!==a&&(b+="<span data-star='"+a+"' class='spacer'></span>");$(".rating-bar-back:not(.js-stared)").after(b).addClass("js-stared")};(function(a){var b=a({});a.subscribe=function(){b.on.apply(b,arguments)};a.unsubscribe=function(){b.off.apply(b,arguments)};a.publish=function(){b.trigger.apply(b,arguments)};a.one=
function(){b.one.apply(b,arguments)}})($);get_time=function(a){var b=(new Date).getTime();a();return(new Date).getTime()-b};(function(){$(t).on("click",".more-list",G);if(FTB.IS_FTC)$(t).on("click",".hid-range",function(a){z(a);_gaq.push(["_trackEvent","Show Range"]);$(this).hide().next().show()})})();Object.keys||(Object.keys=function(a){var b=[],d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.push(d);return b});c.inherits=function(a,b){function d(){}d.prototype=b.prototype;a.prototype=
new d;a.prototype.constructor=a;return a.prototype};c.stopProp=function(a){a=a||c.event;a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0};c.GET=function(){var a={};c.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(b,d,c){a[d]=c});return a};c.set_cookie=function(a,b,d){var v="";d&&(v=new Date,v.setTime(v.getTime()+36E5*d),v="; expires="+v.toGMTString());d=null;var h=c.location.host.match(/\.?([^.]+)\.[^.]+.?$/);null!=h&&(d=h[0]);t.cookie=a+"="+encodeURIComponent(b)+v+"; path=/"+(null!=
d?"; domain="+d:"")};c.get_cookie=function(a){a+="=";for(var b=t.cookie.split(";"),d=0;d<b.length;d++){for(var c=b[d];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(a))return c.substring(a.length,c.length)}return null};c.add_commas=function(a){if(isNaN(a))return a;a=(a+"").split(".");return"-"===a[0].charAt(0)?"-"+k(a[0].substr(1))+(a[1]?"."+a[1]:""):k(a[0])+(a[1]?"."+a[1]:"")};c.split_template=function(a){a=a.replace(/(^\{|\}$)+/g,"").split("}{");return 1===a.length&&""===a[0]?[]:a};
c.get_img_url=function(a,b,d){if(!b)return"";if(default_imgs[b])return use_svg?(FTB.IS_LOCAL?"":"http://img1.findthebest.com")+"/rx/img/"+default_imgs[b].file_name:"";a||(a=FTB.intl_of||FTB.clone_of||FTB.app_id);a="/sites/default/files/"+a+"/media/images/"+(d?d+"/":"")+b;if(FTB.use_image_cdn){if(A[b])return"http://img"+A[b]+".findthebest.com"+a;p=3===p?1:p+1;A[b]=p;return"http://img"+p+".findthebest.com"+a}return a};c.get_detail_url=function(a,b){return"/l/"+a+(b?"/"+F(b):"")};c.get_compare_url=function(a,
b){if(!b||!b.length)throw Error("Invalid items");b.sort(function(a,b){return a.id-b.id});for(var d="",c="",h=0;h<b.length;h++){if(!b[h].id||!b[h].full_title)throw Error("Listing_id or full_title missing");d+=(0===h?"":"-vs-")+b[h].full_title;c+=(0===h?"":"-")+b[h].id}return a+"/compare/"+c+"/"+d};c.cancelEvent=z;c.fancy_select_bind=s;c.fancy_select_initialize=function(a){var b=$(a?a:"select");if(b.length){var d;b.each(function(){d=$(this);d.parent().hasClass("fancy-select-container")||d.wrap('<div class="fancy-select-container btn"/>').after('<span class="fancy-select bg_grad"><span class="val"/><div class="arrow"/></span>')});
s(a)}};c.encode_title=F;c.decode_title=function(a){return(a+"").replace(/-And-/g,"&").replace(/-/g," ")};c.unserialize_info=function(a){a=decodeURIComponent(a);a=a.split(/&/);for(var b={},d,c=0;c<a.length;c++)d=a[c].split(/=/),b[d[0]]=d[1];return b};c.debounce=function(a,b,d){var c,h;return function(){var k=this,p=arguments,s=d&&!c;clearTimeout(c);c=setTimeout(function(){c=null;d||(h=a.apply(k,p))},b);s&&(h=a.apply(k,p));return h}};c.throttle=function(a,b,c){var k,h,p,s=null,t=0;c||(c={});var z=function(){t=
!1===c.leading?0:new Date;s=null;p=a.apply(k,h)};return function(){var g=new Date;t||!1!==c.leading||(t=g);var A=b-(g-t);k=this;h=arguments;0>=A?(clearTimeout(s),s=null,t=g,p=a.apply(k,h)):s||!1===c.trailing||(s=setTimeout(z,A));return p}};c.once=function(a){var b=!1,c;return function(){if(b)return c;b=!0;c=a.apply(this,arguments);a=null;return c}};c.tt=function(a){return FTB.t&&FTB.t.dict?FTB.t.dict[a]||a:a};c.to_english=function(a){var b=FTB.t&&FTB.t.dict?FTB.t.dict:"";if(b)for(var c in b)if(b.hasOwnProperty(c)&&
b[c]===a)return c;return null};c.ftb_gatekeeper=function(a){return a&&FTB&&FTB.gatekeeper?-1!==$.inArray(a,FTB.gatekeeper)?!0:!1:!1};c.sx_scroll_html=function(a,b,c,k){var h="";b&&(h+='<div class="sx-scrollbar"><div class="sx-track"><div class="sx-thumb"><div class="end"></div></div></div></div>');c&&(h+='<div class="sx-scrollbar-x"><div class="sx-track-x"><div class="sx-thumb-x"><div class="end"></div></div></div></div>');k&&(h+='<div style="height:0"><div class="sx-shadow-top"></div></div>');h+=
'<div class="sx-viewport"><div class="sx-overview">'+a+"</div></div>";k&&(h+='<div style="height:0"><div class="sx-shadow-bottom"></div></div>');return h}})(this,document);
(function(c,t,k){function z(n,e,a){n=(0.12-0.07*(n/100))*e>>0;var q=0.3*e>>0,b=0.1*e>>0,c="M "+n+" "+(e-n),d;d='<svg class="viz area-viz">'+('<path stroke-linecap="round" stroke-width="2" stroke="'+a+'" d="'+c+" l 0 -"+b+" "+c+" l "+b+" 0 "+c+" L "+q+" "+(e-q)+'"/>');c="M "+(e-n)+" "+n;d+='<path stroke-linecap="round" stroke-width="2" stroke="'+a+'" d="'+c+" l 0 "+b+" "+c+" l -"+b+" 0 "+c+" L "+(e-q)+" "+q+'"/>';return d+="</svg>"}function s(n,a,f){a=2*(0.9*a/2>>0);n=a/2-4>>0;f=""+('<div class="bg" style="background:'+
f+";width:"+a+"px;height:"+a+'px;">')+'<div class="empty"></div>';f+='<div class="upper-outer" style="border-width:'+n+'px"></div><div class="upper-inner" style="border-width:'+n+'px"></div>';f+='<div class="lower-outer" style="border-width:'+n+'px"></div><div class="lower-inner" style="border-width:'+n+'px"></div>';f+="</div>";return'<div class="viz area-viz">'+f+"</div>"}function F(n,a,f){var q=2*(0.86*a/2>>0),b=0.87*q>>0;n=(1==this.isHighGood?n:100-n)/100*b;for(var c=n/b*q/2,d="",g=1;4>g;g++)var h=
g/4*q/2>>0,d=d+('<path stroke="rgba(255,255,255,.7)" d="M '+h+" "+(q-(g/4*b>>0))+" l "+(q-2*h)+' 0"/>');a='<svg class="viz pyramid-viz" style="width:'+q+"px;height:"+q+"px;margin:"+(a-q)/2+'px;">';a+='<path fill="'+u+'" d="M 0 '+q+" l "+(q/2>>0)+" "+-b+" L "+q+" "+q+' Z"/>';a=a+('<path fill="'+f+'" d="M 0 '+q+" l "+c+" "+-n+" l "+(q-2*c)+" 0 l "+c+" "+n+' Z"/>')+d;a+='<path stroke="rgba(255,255,255,.7)" d="M '+(q/2>>0)+" "+(q-n)+" l 0 "+n+'"/>';return a+="</svg>"}function G(a,e,f){f=100;var q=2100,
b="";60>e?(f=40,q=840,b="smallest"):100>e&&(f=60,q=1260,b="small");a=d(a,f);-1==this.isHighGood&&(a=q+2*f-a);return'<div class="viz pyramid-viz" style="width:'+f+"px;height:"+f+"px;"+("margin:"+((e-f)/2>>0)+"px;")+"background:url(/rx/img/pyramid-ranking-sprite"+(-2==this.isHighGood?"-plain":"")+(b?"_"+b:"")+".png) "+a+'px 0px;"></div>'}function p(a,e,f,q,c,d){c=c?"<span style='font-size:"+(0.65*f>>0)+"px;line-height:"+f+"px;'>"+c+"</span>":"";e=e?"width:"+e+"px;":"";f=f?"height:"+f+"px;":"";d=d||
b(a,q);return'<div class="viz meter-viz" style="'+e+f+";border-color:"+d+'"><div class="color" style="width:'+a+"%;background:"+d+';">'+c+"</div></div>"}function A(a,e,f,b,c,d,g,h,l,k,p){if(""===e)return"";"_small"===f?f=60:"smallest"===f&&(f=40);if(H[a])return(new m[a]).getHTML(e,f);M[a]&&(a=M[a]);if(!m[a]){a&&Q.log("Error: visual type undefined");if(isNaN(e))return(new m.invalid).getHTML(e,f);a="numeric"}a=new m[a];a.init(b+"",c+"",d,g,h,l,k);return a.getHTML(e,f,0,p)}function a(a,e,f,b,c){return'<div style="position:absolute;left:'+
a+"px;top:"+e+"px;width:"+f+"px;height:"+b+"px;"+(c?"background-color:"+c+";":"")+'">'}function b(a,e){return-2==e?E:B[-1==e?70<=a?0:35<=a?1:2:70<=a?2:35<=a?1:0]}function d(a,e){var f=20*(a/100)>>0;e||(e=100);f||(f=1);return(f+1)*e}function v(a,e,f,b,c){var d="",g=Math.abs(a);9995E8<=g?(a/=1E12,d="Trillion"):9995E5<=g?(a/=1E9,d="Billion"):999500<=g?(a/=1E6,d="Million"):999.5<=g&&(a=Math.round(a));d?(g=Math.abs(a),a=100<=g?a.toFixed(0):10<=g?h(a,1):h(a,2),a+=e?'<div class="number_suffix"'+(c?' style="font-size:'+
c+'px"':"")+">"+d+"</div>":d.charAt(0)):(-1<b&&(e=(a+"").split("."),e[1]&&e[1].length>b&&(a=h(a,b))),f&&(a=add_commas(a)));return a}function h(a,e){return Math.round(a*Math.pow(10,e))/Math.pow(10,e)}function N(a,e,f){if(f){if(!f.shiftKey&&!f.ctrlKey)return;cancelEvent(f)}e=$(e).css("overflow","visible");(R[a]||C)(e)}function C(a){a.css({transition:".55s","z-index":1100});(function f(){var b="translate3d("+(1E3*Math.random()-500)+"px,"+(1E3*Math.random()-500)+"px,0) rotate3d("+Math.random()+","+Math.random()+
","+Math.random()+","+360*Math.random()+"deg) scale3d("+(3*Math.random()+0.3)+","+(3*Math.random()+0.3)+","+(3*Math.random()+0.3)+")";a.css({transform:b});setTimeout(f,600)})()}function I(a,e,f,b,c){this.value=e;this.width=f;var d=new J;c&&(d.color=c);this.viz=$(d.getHTML(e,f));$(a).append(this.viz);b&&this.animate()}function L(a,e,f){"_small"==e?e=60:"smallest"==e&&(e=40);var b=new J;f&&(b.color=f);return b.getHTML(a,e)}k=c.viz||{};var g=c.inherits,Q=c.console,u="#ccc",E="#999",B=["#eb756e","#ffdb49",
"#b2d764",u],M={currency:"horizontal-meter"},H={"smart-rating":"smart-rating",yesno:"yesno"},m=[],K=!!c.use_svg;c.ftb_mobile&&(K=!1);K||(M.population="size-blocks",M.speedometer="quantity-stack",M["time-circle"]="quantity-stack",M.pie="quantity-stack");var D=m.invalid=function(){},y=D.prototype;y.minWidth=40;y.width=100;y.height=100;y.fontMultiplier=1;y.init=function(){};y.getViz=function(){return""};y.getHTML=function(a,e){e&&(this.width=e=e<this.minWidth?this.minWidth:e);return'<div class="viz-wrap" style="width:'+
e+"px;height:"+e+'px;"><div class="val">'+a+"</div></div>"};y.getValueString=function(a,e,f,b,c,d,g){!c||1E3<=a?(c=this.getFontSize("loldontcare",e),a=v(a,!g,this.addCommas,d,c)):(d=(a+"").split("."),a>>=0,d[1]>>0&&(a+='<span class="decimal">'+d[1]+"</span>"));return'<div class="val" style="line-height:'+e+"px;font-size:"+f+"px;"+(b?"color:"+b+";":"")+'">'+(this.prefix?'<span class="pre">'+this.prefix+"</span>":"")+a+this.suffix+"</div>"};y.getFontSize=function(a,e){var f=(a+"").length;return Math.max(9,
this.fontMultiplier*(Math.round(28-(f+5)/(f+1)*f)+(0.14*(e-100)>>0)))};y.getFontColor=function(){return""};y.animate=function(){};var r=m.numeric=function(){},x=g(r,D);k.Numeric=r;x.type="numeric";x.prefix="";x.suffix="";x.suffixPlacement="auto";x.medianArray=[];x.isHighGood=-2;x.calcType="chop";x.addCommas=!0;x.allowZeroPercent=!1;x.forceInlineSuffix=!1;x.longSuffix="";x.getFontSize=function(a,e){return y.getFontSize.call(this,this.prefix+v(a,!1,this.addCommas)+this.suffix,e)};x.init=function(a,
e,f,b,c,d,g){a&&(this.prefix=a);e&&(this.suffix=e);g&&(this.suffixPlacement=g);f&&(this.medianArray=f.split("|"));b&&(this.isHighGood=b);c&&(this.calcType=c);this.addCommas=1==d;this.forceInlineSuffix?this.suffixPlacement="inline":"auto"===this.suffixPlacement&&(2<this.suffix.length||2==this.suffix.length&&" "!=this.suffix.charAt(0)&&":"!=this.suffix.charAt(0))&&(this.suffixPlacement="below");"below"===this.suffixPlacement&&(this.longSuffix='<span class="viz-suffix">'+this.suffix+"</span>",this.suffix=
"");2<this.prefix.length&&(this.prefix="")};x.getHTML=function(a,e,f,b){e&&(this.width=e<this.minWidth?this.minWidth:e);this.height=f||this.width;e=this.getPercent(a);b=b||this.getColor(e);b=this.getViz(e,this.width,b,a);f=this.getFontSize(a,this.width);e=this.getFontColor(e);a=this.getValueString(a,this.width,f,e,"currency"==this.type);return this.getWrapHTML(b+a)};x.getWrapHTML=function(a){return'<div class="viz-wrap '+this.type+'" style="width:'+this.width+"px;height:"+this.height+'px;">'+a+"</div>"+
this.longSuffix};x.getPercent=function(a){if(!this.medianArray.length)return a;a=(a+"").replace(/,/g,"");var e=0,f=this.medianArray,b=f[0],c=f[20];if("medians"==this.calcType)for(a=parseFloat(a),b=20;0<=b;b--){if(a>=parseFloat(f[b])){e=5*b;break}}else"chop"==this.calcType?(e=f[1],e=100*((a-e)/(f[19]-e))):"percent"==this.calcType?e=a:"minmax"==this.calcType?e=100*((a-b)/(c-b)):"zero"==this.calcType?e=100*(a/c):"allmax"==this.calcType?e=-1==this.isHighGood?0:100:"zeroten"==this.calcType?e=10*a:"zerofive"==
this.calcType&&(e=20*a);e=Math.round(e);0>e&&(e=0);100<e&&(e=100);0!==e||this.allowZeroPercent||(e=1);return e};x.getColorCutoffs=function(){if(-2==this.isHighGood)return[100,0];for(var a=this.medianArray[0],e=this.medianArray[20],f,b,c=(e-a)/200,d=this.getColor(0),g=parseFloat(a),h,l=0;200>l;l++){h=this.getColor(this.getPercent(g));if(h!==d)if(!f)f=100*((g-a)/(e-a)),d=h;else if(!b){b=100*((g-a)/(e-a))-f;break}g+=c}return[f,b]};x.getColor=function(a){return b(a,this.isHighGood)};var J=m["smart-rating"]=
function(){this.type="smart-rating";this.width=94},l=g(J,D);l.color="";l.getHTML=function(a,e){var f="",b="";0>=a?(f="Unrated",b=0):(f=Math.round(100*parseFloat(a))/5,b=Math.round(20*a));e&&(this.width=e=e<this.minWidth?this.minWidth:e);return'<div class="viz-wrap '+this.type+'" style="width:'+e+"px;height:"+e+'px;" title="'+f+'">'+this.getViz(b,e)+"</div>"};l.getViz=function(a,e){if(K){var f=a,b=this.color;b||(b=B[0],75<=f?b=B[2]:40<=f?b=B[1]:f||(f="",b=u));var c=0.9*e>>0,d=c/86;return'<svg class="smart-viz" style="margin:'+
((e-c)/2>>0)+'px;" width="'+c+'" height="'+c+'">'+(1!=d?'<g transform="scale('+d+')">':"")+'<circle class="color" cx="43" cy="43" r="42" fill="'+b+'"/><circle class="ring" cx="43" cy="43" r="23" fill="#fff"/>'+(f?'<polygon points="43 7 51 23 35 23" fill="#fff" transform="rotate('+(360*(f/100)>>0)+' 43 43)"/>':"")+(f?'<text x="43" y="51" text-anchor="middle" fill="#4d4d4d">'+f+"</text>":'<text class="unrated" x="43" y="32" text-anchor="middle" fill="'+u+'">NOT<tspan x="43" y="45">YET</tspan><tspan x="43" y="58">RATED</tspan></text>')+
(1!=d?"</g>":"")+"</svg>"}f=0.9*e>>0;c=0;b=1;d=0;84<=f?f=84:52<=f?(f=52,b=-93,d=-8):(f=35,b=-155,d=-24);a?c=5>a?1:a/5>>0:(c=0,a="");c=-(f+10)*c+1;f+=2;d="font-size:"+this.getFontSize(a,f+d)+"px;";return'<div class="smart-viz" style="'+("width:"+f+"px;height:"+f+"px;line-height:"+f+"px;")+d+("margin:"+((e-f)/2>>0)+"px;")+("background:url(/rx/img/smart_rating_all.png) no-repeat "+c+"px "+b+"px;")+'">'+a+"</div>"};l=m["horizontal-meter"]=function(){this.type="horizontal-meter"};g(l,r).getViz=function(a,
e,f){return p(a,"","",this.isHighGood)};l=m["time-circle"]=function(){this.type="time-circle"};g(l,r).getViz=function(a,e,f,b,c){c||(c="#e9e9e9");f&&-1!==f?B[f]&&(f=B[f]):f=this.getColor(a);b=e/100;var d=2*(a/100)*Math.PI,g=50+40*Math.sin(d),h=50+40*Math.cos(d+Math.PI);return'<svg class="viz ring-viz" width="'+e+'" height="'+e+'">'+(1!=b?'<g transform="scale('+b+')">':"")+'<circle cx="50" cy="50" r="40" stroke-width="9" stroke="'+c+'" fill="none"/>'+(0.001>100-a?'<circle class="color" cx="50" cy="50" r="40" stroke="'+
f+'" stroke-width="9" fill="none"/>':'<path class="color" d="M 50 10 A 40 40 0 '+(d>Math.PI?"1 1 ":"0 1 ")+g+" "+h+'" stroke="'+f+'" stroke-width="9" fill="none"/>')+(1!=b?"</g>":"")+"</svg>"};k.TimeCircle=l;l=m["quantity-stack"]=function(){this.type="quantity-stack"};l=g(l,r);l.fontMultiplier=0.85;l.getViz=function(a,e,f){return'<div class="viz stack-viz"><div class="color" style="height:'+(a/100*0.8*e>>0)+"px;background:"+f+';"></div></div>'};l=m.battery=function(){this.type="battery"};g(l,r).getViz=
function(a,e,f){return'<div class="viz battery-viz"><div class="cap"></div><div class="color" style="width:'+a+"%;background-color:"+f+';"></div></div>'};l=m["area-square"]=function(){this.type="area-square"};l=g(l,r);l.getViz=function(a,e,f){var b=2*(0.88*e/2>>0);e=(e-b)/2;a=2*((a?a:5)*b/100/2>>0);var c=(b-a)/2,b='<div class="viz '+this.type+'-viz" style="'+("width:"+b+"px;height:"+b+"px;top:"+e+"px;left:"+e+"px;")+"background:"+u+';">';return b+='<div class="color" style="'+("width:"+a+"px;height:"+
a+"px;top:"+c+"px;left:"+c+"px;")+"background:"+f+";border-color:"+E+';"></div></div>'};var P=m["area-circle"]=function(){this.type="area-circle"};g(P,r).getViz=l.getViz;l=m["size-blocks"]=function(){this.type="size-blocks"};g(l,r).getViz=function(a,e,f){a=20*(a/100)>>0;e=(0.6*e-12)/6;for(var b='<div class="viz blocks-viz">',c=0,d=[6,5,4,3,2,1],g=0;21>g;g++){var h=c*(e+2),l=(6-c-d[c])*(e+2);0===--d[c]&&c++;b+='<div class="block" style="bottom:'+h+"px;left:"+l+"px;width:"+e+"px;height:"+e+"px;background:"+
(g<=a?f:"#e9e9e9")+';"></div>'}return b+"</div>"};l=m["area-arrows"]=function(){this.type="area-arrows"};g(l,r).getViz=K?z:s;l=m["star-rating"]=function(){this.type="star-rating"};l=g(l,r);l.allowZeroPercent=!0;l.getViz=function(a,e){var f=100;60>e?f=40:100>e&&(f=60);var b="width:"+f+"px;height:"+f+"px;",c="margin:"+((e-f)/2>>0)+"px;",g=this.type,h=this.isHighGood,l=100,k="";40>=f?(k="smallest",l=40):60>=f&&(k="small",l=60);f=d(a,l);return'<div class="viz sprite" style="'+b+c+("background:url(/rx/img/"+
(g+"-sprite"+(-2==h?"-plain":-1==h?"-reverse":"")+(k?"_"+k:"")+".png")+") "+f+"px 0px;")+'"></div>'};l=m["ratio-square"]=function(){this.type="ratio-square"};g(l,r).getViz=function(b,e,f,c){b=0.04;var d,g,h=2;g=36>=this.medianArray[19]?Math.min(Math.round(c),36):Math.min(Math.round(36*(c/this.medianArray[19])),36);25<g?(d=0.083,c=6,h=1):16<g?(d=0.095,c=5):9<g?(d=0.125,c=4):4<g?(d=0.166,c=3):1<g?(d=0.19,b=0.06,c=2):(d=0.22,b=0.13,c=1);var l=Math.ceil(g/c),k=d*e>>0;b=b*e>>0;var m=0.45*e>>0,p,s;d="";
for(var r=0;r<g;r++)s=r%c,p=r/c>>0,d+=a(s*(k+h)+b,p*(k+h)+m,k,k,f)+"</div>";e=a(0.78*e-k/2>>0,m+l*k/2-k/2>>0,k,k,u)+"</div>";return""+('<div class="viz ratio-viz">'+d+e+"</div>")};l=m.pyramid=function(){this.type="pyramid"};l=g(l,r);l.prefix="#";l.init=function(){x.init.apply(this,arguments);1!==+this.isHighGood&&(this.isHighGood=-1)};l.getViz=K?F:G;l=m.population=function(){this.type="population"};g(l,r).getViz=function(a,e,b){a=12*(a/100)>>0;var c=Math.round(0.07*e),d=0.1*e,g=2*Math.round(d/2),
h=2*Math.round(0.06*e/2),k=2*Math.round(0.2*e/2),l=Math.round(0.115*e);a||(a=1);c='<circle cx="0" cy="-'+Math.round(c/2)+'" r="'+c/2+'"/><rect x="-'+g/2+'" y="'+Math.round(c/6)+'" width="'+g+'" height="'+g+'" rx="'+g/4+'" ry="'+g/4+'"/><rect x="-'+h/2+'" y="'+Math.round(c/6)+'" width="'+h+'" height="'+k+'" rx="'+h/4+'" ry="'+h/4+'"/>';g="";for(h=0;12>h;h++)g+='<g transform="translate('+(1.5*(h/2>>0)*d+l)+","+(1.5*~~(h%2)*k+l)+')" fill="'+(h<a?b:"#e9e9e9")+'">'+c+"</g>";return'<svg class="viz pop-viz" width="'+
e+'" height="'+e+'">'+g+"</svg>"};l=m["dollar-signs"]=function(){this.type="dollar-signs"};g(l,r).getHTML=function(a,e,b){e&&(this.width=e<this.minWidth?this.minWidth:e);this.height=b||this.width;b=this.getPercent(a);e=this.getColor(b);var c=Math.min(5,5*(b/100)+1>>0);b="";for(var d=0;d<c;d++)b+="$";for(b+='<span style="color:#e9e9e9">';5>d;d++)b+="$";b+="</span>";d="";this.showNumber&&(this.fontMultiplier=1.2,c=this.getFontSize(a,this.width),d=this.getValueString(a,this.width,c,""));this.prefix=
this.suffix="";this.fontMultiplier=1.25;c=this.getFontSize("$$$$$",this.width);b=this.getValueString(b,this.width,c,e);return this.getWrapHTML(b+d)};P=m["dollar-signz"]=function(){this.type="dollar-signz";this.showNumber=!0};g(P,l);l=m.speedometer=function(){this.type="speedometer"};g(l,r).getViz=function(a,b,c){for(var d=b/100,g,h,k,l=0.8*Math.PI,m=2.2*Math.PI,p=a/100*(m-l)+l,s="",r=l;r<=m;r+=(m-l)/14)a=31*Math.cos(r)+50,g=31*Math.sin(r)+40,h=37*Math.cos(r)+50,k=37*Math.sin(r)+40,s+='<line x1="'+
a+'" y1="'+g+'" x2="'+h+'" y2="'+k+'"/>';a=50;g=40;h=31*Math.cos(p)+50;k=31*Math.sin(p)+40;return'<svg class="viz speed-viz" width="'+b+'" height="'+b+'"><g stroke="'+E+'" stroke-width="2"'+(1!=d?' transform="scale('+d+')"':"")+'><circle cx="50" cy="40" r="4" stroke-width="0" fill="'+c+'"/>'+(s+('<line x1="'+a+'" y1="'+g+'" x2="'+h+'" y2="'+k+'" stroke-width="3" stroke="'+c+'"/>'))+"</g></svg>"};l=m.width=function(){this.type="width"};g(l,r).getViz=function(a,b,c){a=""+('<div class="left" style="border-right-color:'+
c+'"></div>')+('<div class="line" style="background:'+c+'"></div>');a+='<div class="right" style="border-left-color:'+c+'"></div>';return'<div class="viz width-viz">'+a+"</div>"};l=m.height=function(){this.type="height"};g(l,r).getViz=function(a,b,c){a=""+('<div class="top" style="border-bottom-color:'+c+'"></div>')+('<div class="line" style="background:'+c+'"></div>');a+='<div class="bottom" style="border-top-color:'+c+'"></div>';return'<div class="viz height-viz">'+a+"</div>"};l=m.pie=function(){this.type=
"pie"};g(l,r).getHTML=function(a,b){b&&(this.width=b=b<this.minWidth?this.minWidth:b);var c=b,d=this.getPercent(a),g;if("percent"===this.calcType){this.calcType="chop";var h=this.getPercent(a);this.calcType="percent";g=this.getColor(h)}else g=this.getColor(d);var h="",h=b,k=h/100,l=2*(d/100)*Math.PI,m=50+45*Math.sin(l),p=50+45*Math.cos(l+Math.PI),h='<svg class="viz pie-viz" width="'+h+'" height="'+h+'">'+(1!=k?'<g transform="scale('+k+')">':"")+'<circle cx="50" cy="50" r="45" stroke="none" fill="#e9e9e9"/>'+
(0.001>100-d?'<circle class="color" cx="50" cy="50" r="45" stroke="none" fill="'+g+'"/>':'<path class="color" d="M 50 5 A 45 45 0 '+(l>Math.PI?"1 1 ":"0 1 ")+m+" "+p+' L 50 50" stroke="none" fill="'+g+'"/>')+(1!=k?"</g>":"")+"</svg>",c=this.getFontSize(a,c),d=this.getFontColor(d);return'<div class="viz-wrap pie" style="width:'+b+"px;height:"+b+'px;">'+h+this.getValueString(a,b,c,d,!1)+"</div>"+this.longSuffix};l=m["colored-number"]=function(){this.type="colored-number";this.fontMultiplier=1.2};r=
g(l,r);r.getFontColor=r.getColor;r=m.set=function(){this.type="set"};g(r,D).getHTML=function(a,b){b&&(this.width=b=b<this.minWidth?this.minWidth:b);return'<div class="viz-wrap '+this.type+'" style="width:'+b+"px;height:"+b+'px;">'+this.getViz(a,b,"")+"</div>"};D=m.yesno=function(){this.type="yesno"};g(D,r).getViz=function(a,b,c){c||(c=a>>0?B[2]:B[0]);return'<div class="viz yesno-viz" style="color:'+c+";font-size:"+(0.2*b>>0)+"px;height:"+b+"px;line-height:"+b+'px;">'+(a>>0?"yes":"no")+"</div>"};k._pieSlice=
function(a,b,c,d,g,h){var k=g-d;if(0.001>2*Math.PI-k)return'<circle cx="'+a+'" cy="'+b+'" r="'+c+'" fill="'+h+'"/>';var l=a+Math.sin(d)*c;d=b-Math.cos(d)*c;var m=a+Math.sin(g)*c;g=b-Math.cos(g)*c;return'<path d="M '+l+" "+d+" A "+c+" "+c+" 0 "+(k>Math.PI?"1 1 ":"0 1 ")+m+" "+g+" L "+a+" "+b+' Z" fill="'+h+'"/>'};k.meter_viz=p;k.display=A;k.animate=N;var R={"smart-rating":function(a){function b(){k<l&&setTimeout(b,6);c.attr("transform","rotate("+360*(k/100)+" 43 43)");d.text(k>>0);h||g.attr("fill",
75<=k?B[2]:40<=k?B[1]:B[0]);k+=(0.008*(l/2-k)+0.5)*l/100}var c=a.find("polygon"),d=a.find("text"),g=a.find(".color"),h=-1==B.indexOf(g.attr("fill")),k=0,l=d.text()>>0;l&&b()},"quantity-stack":function(a){a=a.find(".color");var b=a.height();a.height(0);a.animate({height:b},1E3)},"horizontal-meter":function(a){var b=a.find(".color"),c=b.width();b.css({width:0});setTimeout(function(){b.animate({width:c},1200)},200)},"size-blocks":function(a){function b(){21>g&&setTimeout(b,100);$(c[g]).animate({opacity:1,
left:d[g]},1E3,"linear");g++}var c=a.find(".block"),d=[];for(a=0;21>a;a++)d[a]=$(c[a]).css("left");c.css({opacity:0,left:100,rotate:0});var g=0;b()},pyramid:function(a){var b=a.find("path"),c=0;(function w(){c++;c%=360;b.attr("fill","hsl("+c+",80%,50%)");setTimeout(w,5)})()},"ratio-blocks":function(a){var b=a.width(),c=a.height();a.find(".viz").append(a.find(".viz>div").clone());a.find(".viz>div").each(function(){$(this).animate({left:(400*Math.random()-200>>0)+b/2,top:(400*Math.random()-200>>0)+
c/2},500)})}};$(t).on("click",".viz-wrap",function(a){N(this.className.split(" ")[1],this,a)});k.Smart=I;I.prototype.animate=function(){smart_animate(this.viz)};k.Meter=function(a,b,c,d,g,h,k){this.viz=$(p(b,c,d,g,h));$(a).append(this.viz);k&&meter_animate(this.viz)};k.all=function(){var a;a='<img style="display:block;margin:0 auto;height:200px;" src="http://i.imgflip.com/1bh9.jpg"/><table style="margin:0 0 20px;"><tr><td>SIZE</td>';var b=[],c;for(c in m)({currency:1,numeric:1,invalid:1,set:1})[c]||
H[c]||(a+="<th>"+c+"</th>",b[c]=new m[c],b[c].init("","","0|1|2|2|2|2|2|2|2|3|3|3|3|3|3|4|4|4|4|5|5",1,"",!0));a+="</tr>";for(var d=40;120>d;d+=20){a+="<tr><td>"+d+"x"+d+"</td>";for(c in b)a+="<td>"+b[c].getHTML((500*Math.random()>>0)/100+"",d)+"</td>";a+="</tr>"}return a+="</tr></table>"};k.render=function(a){for(var b,c,d,g=0;g<a.length;g++)for(c=a[g],b=0;b<c.vals.length;)d="smart-rating"===c.type?L(c.vals[b+1],c.vals[b+2]):A(c.type,c.vals[b+1],c.vals[b+2],c.pre,c.suf,c.medians,c.high_good,c.calc,
c.commas,c.suf_placement),$("#vz"+c.vals[b]).replaceWith(d),b+=3};c.viz=k;c.disp_rating=L;c.rectOpen=a;c.big_number_format=v})(window,document);
window.FTB&&(FTB.flag=function(c,t){FTB.full_site_spin();$.get("/ajax_flag",{type:c,data:t},function(c){FTB.remove_site_spin();BOX.show({html:c,w:600});$(".BOX .flag-submit").one("click",function(){var c={};$(this).closest(".flag-form").find("input, textarea, select").each(function(){var k=$(this);c[k.attr("name")]=k.val()});$.get("/ajax_flag_update",{data:c},function(){$(".BOX .flag-wrap").html("<div class='flag-message'><span class='success-icon'></span><p>Thanks! We will review the flag and make the appropriate changes</p></div>")})})})});
