(function(b){function a(a,c,b){this.app_id=a;this.list=[];this.list_ids=[];this.init(b||"body")}var c=new Persist.Store("rcq",{expires:2});a.prototype={init:function(a){var c=this;c.$rcq=$('<div class="rcq"><div class="rcq-compare-q clearfix"><div class="rcq-now-comparing">'+tt("Now Comparing")+' (<span class="rcq-count"></span>)</div><ul class="rcq-listings"></ul><div class="rcq-compare-btn-wrap"><div class="rcq-compare-btn stnd-btn bg-blue">'+tt("Compare Selected Items")+'</div><div class="rcq-more-msg">'+
tt("Select at least 2 listings to compare")+'</div></div><div class="rcq-clear">'+tt("Clear all")+"</div></div></div>").on("click",".rcq-compare-btn",function(){c.compare()}).on("click",".rcq-clear",function(){b.srp&&_gaq.push(["_trackEvent","SRP","Compare Queue","Clear All"]);c.clear()}).on("click",".rcq-item a",function(a){if(b.srp)return EVT(["SRP","Compare Queue","Clicked Listing Link"],this,a)}).on("click",".checkbox",function(){c.remove($(this).closest(".rcq-item").data("listing-id"))}).appendTo(a);
c.$rcq.before('<div class="rcq-open-close open no-sel"><span class="toggle nosel"></span></div>');c.$rcq_open_close=$(".rcq-open-close");c.$rcq_open_close.on("click",function(){if(!c.$rcq.is(":animated")){var a=$(this).hasClass("closed");b.srp&&_gaq.push(["_trackEvent","SRP","Compare Queue",a?"Opened":"Closed"]);c.toggle(a)}})},add:function(a,b,d,g,k){var f=this.$rcq,l=this.$rcq_open_close,n=this.list;if(-1===this.list_ids.indexOf(a)&&10>n.length)n.push([a,b,d,g]),this.list_ids.push(a),f.find(".rcq-count").text(n.length),
b=$('<li class="rcq-item rcq-item'+a+'"><div class="compare-item-wrap"><div class="checkbox checked">&times</div><div class="compare-item"><a href="/l/'+a+"/"+d+'"><div class="image">'+(g?'<img src="'+g+'"/>':"")+'</div><div class="name"><span>'+b+"</span></div></a></div></div></li>").data("listing-id",a),f.find(".rcq-listings").append(b),1==n.length?(f.show(),l.show(),$(".scroll-popup").css("bottom",f.outerHeight()),this.toggle(!0,!0),f.find(".rcq-more-msg").show(),f.find(".rcq-compare-btn").hide()):
2===n.length&&(f.find(".rcq-more-msg").hide(),f.find(".rcq-compare-btn").show()),c.set(this.app_id+"",JSON.stringify(n));else return!1;this.onadd&&this.onadd(a);if(k&&"none"!==f.css("display")){var m=f.find(".rcq-item"+a+" .compare-item-wrap");m.show();setTimeout(function(){m.fadeOut(800,function(){m.css("display","")})},700)}$.publish("rcq/change");return n.length},remove:function(a){var b=this.$rcq,d=this.$rcq_open_close,g=this.list,k=this.list_ids.indexOf(a);if(-1===k)return!1;g.splice(k,1);this.list_ids.splice(k,
1);b.find(".rcq-count").html(g.length);b.find(".rcq-item"+a).remove();0<g.length?c.set(this.app_id+"",JSON.stringify(g)):c.remove(this.app_id+"");0===g.length?(b.hide(),d.hide(),$(".scroll-popup").css("bottom",0)):1===g.length&&(b.find(".rcq-more-msg").show(),b.find(".rcq-compare-btn").hide());this.onremove&&this.onremove(a);$.publish("rcq/change");return g.length},populate:function(){this.list.length&&this.$rcq.find(".rcq-item").remove();this.list=[];this.list_ids=[];if(val=c.get(this.app_id+""))for(var a=
JSON.parse(val),b=0;b<a.length;b++)this.add(a[b][0],a[b][1],a[b][2],a[b][3]);$.publish("rcq/init")},clear:function(){for(var a=this.list,c=a.length-1;0<=c;c--)this.remove(a[c][0]);$.publish("rcq/change")},toggle:function(a,c){var b=this.$rcq;this.$rcq_open_close.removeClass(a?"closed":"open").addClass(a?"open":"closed");c?b.css("bottom",a?0:-b.outerHeight()+0):b.stop().animate({bottom:a?0:-b.outerHeight()+0})},compare:function(){var a=this.get_compare_url();if(!a)return!1;b.location!==b.parent.location?
b.open(a):b.location=a;return!0},get_compare_url:function(){if(!a&&this.app_id!=FTB.app_id)throw Error("Unable to get base_url");var a=a||"",c=this.list,b=[],g;if(2>c.length)return"";for(g=0;g<c.length;g++)b.push({id:c[g][0],full_title:c[g][2]});return get_compare_url(a,b)}};b.RCQ=a})(window);var detail=detail||{};
detail.remove_component=function(b){if(b&&b.length){var a=b.closest(".detail-section"),c;c=a.find(".data-block-body > tbody > tr");if(a.length&&1===c.length){b=a.attr("data-section-id");$(".section-nav."+b).remove();for(c=0;c<detail.sections.length;c+=1)"id-"+detail.sections[c].id===b&&(detail.sections[c]=void 0);a.remove()}else a=b.closest(".data-block"),c=a.find(".data-block-body > tbody > tr"),a.length&&1===c.length?a.remove():b.remove()}};
(function(b){(new RCQ(FTB.app_id)).populate();if(detail.rand_classes){var a,c,h,e;for(b=0;b<detail.rand_classes.length;b+=1)if(a=detail.rand_classes[b],a=$("."+a),c=a.length)for(h=Math.floor(Math.random()*c),e=0;e<c;e+=1)e!==h?detail.remove_component(a.eq(e)):a.eq(e).css("display","table-row")}})(document);
(function(){var b=$("#detail-float");$("body");var a=!1,c,h="",e;$(window).scroll(function(){var d=$(window).scrollTop(),g=$("#detail-sections").offset().top-25;!a&&d>g?(b.show(),setTimeout(function(){b.addClass("floating");b.find("#float-right")&&$(window).resize()},0),a=!0):a&&d+0<g&&(b.removeClass("floating"),a=!1);a&&(clearTimeout(c),c=setTimeout(function(){var a=detail.sections,c,b,g,m=!1;for(c=a.length-1;0<=c;c-=1)if(b=a[c])b.node||(b.node=$(".detail-section.id-"+b.id),b.float_node=$("#detail-float .id-"+
b.id+" .current")),m||(g=100*((d-b.node.offset().top+82)/b.node.height()),g=0>g?0:Math.min(g,100),0!==g&&(m=!0,e=b.float_node.parent().text(),e!==h&&($(window).trigger("section-change",e),$(".section-nav.c").removeClass("c"),b.float_node.parent().addClass("c"),h=e)))},150))}).scroll();$("body").on("click",".section-nav",function(){var a=$(this).attr("data-section-id");FTB.go_to($(".detail-section.id-"+a),-50,!1,500);setTimeout(function(){$(window).scroll()},1E3)}).on("click",".top-link",function(){$("html, body").animate({scrollTop:0},
600);setTimeout(function(){$(window).scroll()},1E3)});$("#detail-float .float-item").on("click",function(){var a=parseInt($("body").css("margin-top"),10),a=$("#detail-wrap").offset().top-a;$("html, body").animate({scrollTop:a},600);setTimeout(function(){$(window).scroll()},1E3)})})();
(function(b,a){var c=b.location.hash;c&&(c=c.substring(1).split("/"),"review"===c[0]&&$(function(){"add"===c[1]?$(".add-review-button:eq(0)").click():1===c.length?setTimeout(function(){FTB.go_to($("#rr-wrap"),void 0,!0)},20):detail.urr.rev_popup(parseInt(c[1],10))}))})(window,document);
(function(){$("#img-thumbs").each(function(){var b=$(this),a;a=b.closest(".vert-thumbs")[0]?"y":"x";b.tinyscrollbar_build({axis:a,hide_until_hover:!1})});$(".imagenew.component, #detail-image").each(function(){var b=$(this),a=b.find(".dd-img"),c=b.find(".dd-thumb"),h=b.find(".img-attr-alt"),e=b.find(".img-attr-attr"),d=b.find(".img-attr");tiny_image=function(){_gaq.push(["_trackEvent","Detail Page","Images","large"]);var a=$(this).find("img").attr("src");new ImageViewer(dd_imgs,a)};h.text()||e.text()||
d.css("display","none");c.mouseenter(function(){var b=$(this),k=b.find("img"),f;f=b.attr("data-attr");b=b.attr("data-alt");k=k.attr("src");_gaq.push(["_trackEvent","Detail Page","Images","hover"]);a.attr("src",k);e.text(f);h.text(b);f==b&&(e.text(f),h.text(""));f||b?d.css("display","block"):d.css("display","none");c.removeClass("selected");$(this).addClass("selected")});a.parent().on("click",tiny_image);c.on("click",tiny_image)})})();
if(FTB.IS_EMPLOYEE){$(document).on("click",".edit-field-icon",function(b){stopProp(b);$this_edit_row=$(this);$("#F-sidebar")[0]?("none"===$("#F-sidebar").css("display")&&$("#F-sidebar").show(),grab_field()):window.F.toggle(function(){dd_edit_fields=$(".fd-drag");num_dd_edit_fields=dd_edit_fields.length;grab_field()})});$("td.fname").hover(function(){$(this).find(".edit-field-icon").show()},function(){$(this).find(".edit-field-icon").hide()});$(".edit-field-icon-div").hover(function(){$(this).children(".edit-field-icon").show()});
var grab_field=function(){var b=$this_edit_row.data("name");for(i=0;i<num_dd_edit_fields;i++)if(b===$(dd_edit_fields[i]).text()){$(dd_edit_fields[i]).click();break}}}$(document).on("click",".edit-button",function(b,a){var c=$(this),h=c.attr("data-editid"),h="/edit_header/?bodyonly&new&item_id="+detail.id+"&header_id="+h;a||FTB.user.uid?BOX.show({iframe:h,w:850,h:650,pad:10}):(window.show_login_dlg(void 0,"Please login to edit this listing."),FTB.onlogin=function(){c.trigger("click",[!0])})});
window.set_edit_height=function(b){b=Math.max(b,550);$(".BOX").height("");$(".BOX iframe").height(b+10)};(function(b,a){a.referrer&&(b.GET().pending_edit&&/\/edit_listing/i.test(a.referrer))&&BOX.show({iframe:"/submission-pending-review?bodyonly",w:850,h:329,fixed:!0})})(window,document);
detail.format_tweet=function(b,a){if(b.possibly_sensitive)return"";var c="<div class='tweet'>",h;a&&(c="<div class='tweet last'>");h=b.text.replace(/((https?|s?ftp|ssh)\:\/\/[^"\s<\>]*[^.,;'">\:\s<\>\)\]\!])/g,function(a){return'<a href="'+a+'" target="_blank">'+a+"</a>"}).replace(/\B@([_a-z0-9]+)/ig,function(a){return a.charAt(0)+'<a target="_blank" href="http://twitter.com/'+a.substring(1)+'">'+a.substring(1)+"</a>"});c=c+("<div class='tweet-text'>"+h+"</div>")+("<div class='tweet-time'><a href='http://twitter.com/"+
b.user.screen_name+"/status/"+b.id_str+"' target='_blank'>by "+b.user.name+" "+detail.relative_time(b.created_at)+"</a></div>");return c+="</div>"};
detail.relative_time=function(b){b=b.split(" ");var a;b=b[1]+" "+b[2]+", "+b[5]+" "+b[3];a=Date.parse(b);b=new Date;a=parseInt((b.getTime()-a)/1E3,10);a+=60*b.getTimezoneOffset();return 60>a?"less than a minute ago":120>a?"about a minute ago":3600>a?parseInt(a/60,10).toString()+" minutes ago":7200>a?"about an hour ago":86400>a?"about "+parseInt(a/3600,10).toString()+" hours ago":172800>a?"yesterday":parseInt(a/86400,10).toString()+" days ago"};
detail.chart_init=function(){$(".bar-chart:visible .bar").each(function(){var b=$(this);b.find(".label").css("maxWidth",b.width()-b.find(".val").outerWidth()-5)});$(".split-row").each(function(){$(this).find(".bar-chart:visible .bar").each(function(){var b=$(this);$(window).resize(function(){b.find(".label").css("maxWidth",$(".detail-split-left").outerWidth()-b.find(".val").outerWidth()-35)})})})};$(detail.chart_init);
$(".car_init").each(function(){var b=$(this),a=b.find(".nav_ctrls"),c=0,h=b.find(".car_item").eq(0),e=b.find(".car_item").length-1;b.css("height",b.css("height"));b.go_to=function(d){c!==d&&(0>d&&(d=e),d>e&&(d=0),h.fadeOut(100),h=b.find(".car_item_"+d).delay(100).fadeIn(100),a.find(".marker").removeClass("enabled"),a.find(".mark_"+d).addClass("enabled"),c=d,setTimeout(detail.chart_init,100))};a.on("click",".left",function(){b.go_to(c-1)});a.on("click",".right",function(){b.go_to(c+1)});a.on("click",
'.marker:not(".enabled")',function(){b.go_to($(this).attr("data-index"))})});$(document).on("click",".see-all-rev",function(){FTB.go_to($("#user-reviews"));FTB.go_to($("#rr-wrap"))});
$(function(){window.applyTips();$("#embed_butt").click(function(){embed({app_id:FTB.app_id,subdomain:FTB.subdomain,app_name:FTB.app_name,type:"detail",ids:[detail.id],listing_title:detail.title,listing_url:"http://"+location.host+location.pathname})});$(document).on("click",".show_rest",function(){$(this).hide().next().show();return!1});if(window.smart_rating_pie)$(document).on("click","#detail-ftb-rating .smart-rating",show_rating_breakdown);$(document).on("click",".tab-nav",function(){var b=$(this),
a;tab_nav_id=b.attr("tab-nav-id");$tab=$("[data-tab-id="+tab_nav_id+"]");$tab_content=$tab.parent();$tab_content.stop();a=$tab_content.height();$tab_content.height(a);b.addClass("open-tab");b.siblings(".tab-nav").each(function(){$(this).removeClass("open-tab")});$tab.siblings(".detail-tab").each(function(){$(this).removeClass("front-tab")});$tab.addClass("front-tab");$.publish("detail/tab");$.publish("detail/tab_graph");$.publish("detail/tab_map");$(document).trigger("tab_component_switch");b=$tab.height();
$tab_content.height(a);$tab_content.animate({height:b},{duration:500,complete:function(){$(this).css("height","")}})});$(window).resize(window.debounce(function(){$(".videoplayer").each(function(){var b=$(this),a=b.width();rate=400/750;min_height=300;height=a*rate;height=a>min_height/rate?height:min_height;b.css("height",height)})},50)).resize()});
(function(b){var a=$("#more-nav-links"),c=$("#more-nav-dropdown");$("#page").on("click",function(){c.hide();a.removeClass("dropped")});a.on("click",function(a){a.stopPropagation();EVT(["Detail Page","More NavLinks Clicked",this,a]);c.toggle();$(this).toggleClass("dropped")});$(b).resize(function(){66>$("#more-nav-links").width()?$("#more-nav-links").addClass("no-arrow"):$("#more-nav-links").removeClass("no-arrow")})})(window);
(function(b){var a=[],c=[],h=[],e=[],d,g;d=function(){a=a.length?a:$("#s-mobile");c=c.length?c:$("#s-float");h=h.length?h:$("#detail-section-wrapper");e=e.length?e:$(".section-summary")};g=function(){d();a.add(c).on("click",".fs-opts",function(){$(this).parent().removeClass("fs-open")});a.add(c).on("click",".fs-window",function(){var a=$(this).parent(),b;a.hasClass("fs-open")?a.removeClass("fs-open"):(a.addClass("fs-open"),b=a.find(".fs-window"),a.find(".fs-mask").width(b.width()))})};$(b).on("section-change",
function(a,b){c.length&&c.find(".fs-val").text(b)});$(b).on("size-mobile-small",function(){var k=[],f,l,n;d();if(a.length)a.add(c).css("display","block"),h.add(e).css("display","none");else{h.find(".title-text").each(function(){k.push({name:$(this).text(),id:$(this).parent().attr("data-section-id")})});f="<div class='fs-wrap'><div class='fs-window'><div class='fs-val'>Navigate To...</div><div class='fs-arrow'></div></div><div class='fs-opts'>";n=k.length;f+="<div class='fs-opt top-link'>Top</div>";
for(l=0;l<n;l+=1)f+="<div class='fs-opt section-nav' data-section-id='"+k[l].id+"'>"+k[l].name+"</div>";f+="</div>";f+="<div class='fs-mask'></div>";f+="</div>";h.after("<div id='s-mobile'>"+f+"</div>");e.after("<div id='s-float'>"+f+"</div>");g();$(b).trigger("size-mobile-small")}});$(b).on("size-mobile-large size-tablet size-full",function(){d();a.add(c).css("display","none");h.add(e).css("display","")})})(window);
(function(b){var a=$(b),c=[{name:"mobile-all",max:730},{name:"mobile-small",max:640},{name:"mobile-large",min:641,max:730},{name:"tablet",min:731,max:940},{name:"full",min:941}],h=[];$(function(){a.resize(function(){var b;b=c.length;for(var d=a.width(),g=[],k;b;b-=1)k=c[b-1],k.min=k.min||0,k.max=k.max||Number.MAX_VALUE,d>k.min&&d<k.max&&g.push(k.name);b=g.length;for(d=0;d<b;d+=1)-1===$.inArray(g[d],h)&&a.trigger("size-"+g[d]);h=g}).resize()})})(window);
var track_sponsor=function(b,a,c,h,e){$.get("/ajax_sponsor_event",{p:e||"det",n:a,e:c,"lids[]":b,ct:h},function(){},"json")};0<$("a.purchase_button.sponsor_button").length&&track_sponsor(FTB.sponsored_id,0,"i",0);
(function(b){var a=$("#detail-sidebar > div:first.float-block-wrap"),c=!1,h=!1,e=$("<div>",{id:"float-placeholder"}),d=$("#detail-sidebar"),g=$("#sidebar-bottom"),k=!1,f,l=!1,n=!1,m=a.find(".float-block");a.length&&(a&&g.offset().top<$(b).height()-100&&(c=!0,a.detach(),d.append(a)),$(b).scroll(function(){if(!n){var l=$(b).scrollTop(),q=g.offset().top;!c&&q-l<$(b).height()?(c=!0,e.height(a.height()),a.detach(),d.append(a).prepend(e)):c&&!h&&60>q-l?(h=!0,m.css({position:"fixed",top:60})):c&&h&&60<q-
l?(h=!1,m.css({position:"",top:""})):c&&!h&&q-l>$(b).height()?(c=!1,a.detach(),e.remove(),d.prepend(a)):!k&&c&&h&&m.offset().top+m.height()>d.height()+d.offset().top?(k=!0,f=d.find("> .data-block:last"),m.css({position:"absolute",top:d.height()-f.offset().top+d.offset().top-f.height()-m.height()+"px"}),a.css("position","relative")):k&&(c&&h&&l<m.offset().top-60)&&(k=!1,m.css({position:"fixed",top:60}))}}),$(b).resize(function(){var f=$(b).width();!l&&940>f?(n=l=!0,a.detach(),a.attr("style",""),a.find(".float-block").attr("style",
""),$(".id-0.detail-section").before(a)):l&&940<f&&(n=l=!1,e.remove(),k=h=c=!1,a.attr("style",""),a.detach(),d.prepend(a))}).resize())})(window);
$(".hover-scroll").each(function(){var b=$(this),a=b.width(),c=$(this).children(),h=c.eq(0),e=c.eq(1),d=c.eq(2),g=e.children().last(),k=a-g.position().left-g.outerWidth()-d.width(),f=parseInt(h.width(),10),l;h&&(e&&d)&&(e.css("marginLeft",f),d.hover(function m(){l=setTimeout(function(){var a;a=parseInt(e.css("marginLeft"),10);a=Math.max(k+3,a);e.css("marginLeft",a-3);l=setTimeout(m,10)},1)},function(a){EVT(["Detail Page","More links shown through hover scroll right-arrow",this,a]);clearTimeout(l)}).click(function(){$(e).animate({marginLeft:k},
100)}),h.hover(function s(){l=setTimeout(function(){var a;a=parseInt(e.css("marginLeft"),10);a=Math.min(f-3,a);e.css("marginLeft",a+3);l=setTimeout(s,10)},1)},function(){clearTimeout(l)}).click(function(){$(e).animate({marginLeft:f},100)}),$(window).resize(function(){var c=parseInt(e.css("marginLeft"),10);e.css("marginLeft",0);a=b.width();k=a-g.position().left-g.outerWidth()-d.width();f=parseInt(h.width(),10);c<=f?e.css("marginLeft",f):c>k?e.css("marginLeft",k):e.css("marginLeft",c)}),b.is("#float-section-wrapper")&&
$(window).scroll(function(){var a=b.find(".section-nav.c"),c;a.length&&(c=parseInt(e.css("marginLeft"),10),a=a.position().left+a.width()/2,c=Math.min(f,Math.max(k,390-a+c)),e.css("marginLeft",c))}))});
(function(b){$("#content-area").on("click",".section-nav",function(){var a=$(this),b=a.text(),a=a.parent().hasClass("section-summary")?"float":"main-header";_gaq.push(["_trackEvent","Detail Page","Section Link",a]);_gaq.push(["_trackEvent","Detail Page","Section Link Rollup",FTB.app_name+" | "+b]);_gaq.push(["_trackEvent","Detail Page","Section Link Rollup","All | "+b])}).on("click",".float-item",function(){_gaq.push(["_trackEvent","Detail Page","Item Anchor Link"])}).on("click","#detail-actions > a",
function(a){var b=$(this).attr("id");_gaq.push(["_trackEvent","Detail Page","Action Links",b]);return go_soon(this,a)}).on("click",".saved-profile",function(a){_gaq.push(["_trackEvent","Profiles","Linked from saved"]);return go_soon(this,a)}).on("click",".profile-link",function(a){_gaq.push(["_trackEvent","Profiles","Linked from DD"]);return go_soon(this,a)}).on("click",".points",function(a){_gaq.push(["_trackEvent","Profiles","Linked from DD points"]);return go_soon(this,a)}).on("click",".tab-nav",
function(a){_gaq.push(["_trackEvent","Detail Page","Clicked on a tab"]);return go_soon(this,a)}).on("click","#detail-top-nav",function(a){_gaq.push(["_trackEvent","Detail Page","SRP Link"]);return go_soon(this,a)}).on("click","a.purchase_button",function(a){_gaq.push(["_trackEvent","Detail Page","Buy Now Button"]);return go_soon(this,a)}).on("click","a.outbound_lnk, a.outbound_email",function(a){var b=$(this),h=b.hasClass("outbound_lnk")?"Outbound Links":"OUtbound Email";_gaq.push(["_trackEvent",
h,"",b.attr("href")]);_gaq.push(["_trackEvent","Detail Page",h,b.attr("href")]);return go_soon(this,a)}).on("click","a.dir",function(a){_gaq.push(["_trackEvent","Detail Page","Directory Links"]);return go_soon(this,a)}).on("click","a.softjoin_link",function(a){_gaq.push(["_trackEvent","Detail Page","Soft Joins"]);return go_soon(this,a)}).on("click","a.srch",function(a){_gaq.push(["_trackEvent","Detail Page","Related Comparison"]);return go_soon(this,a)}).on("click","a.questions",function(a){_gaq.push(["_trackEvent",
"Detail Page","Item Question"]);return go_soon(this,a)}).on("click","li.adv_qa a",function(a){_gaq.push(["_trackEvent","Detail Page","Comp Question"]);return go_soon(this,a)}).on("click","a.snippet_url",function(a){var b=$(this);_gaq.push(["_trackEvent","Detail Page","Expert Review",b.attr("href")]);_gaq.push(["_trackEvent","Read More - Expert Review","Detail",b.attr("href")]);return go_soon(this,a)}).on("click","a.related",function(a){_gaq.push(["_trackEvent","Detail Page","Related Comps"]);return go_soon(this,
a)}).on("click",".login-button",function(){b.show_login_dlg();_gaq.push(["_trackEvent","Locked Content","Button Clicked"]);FTB.onlogin=function(){_gaq.push(["_trackEvent","Locked Content","Login Successful"]);setTimeout(function(){FTB.reload()},100)}});track_click("#hp_lnk","Detail Page","Clicked to Home")})(window);
(function(){function b(a,b){b.dist.bars&&a.find(".fp-histogram").html(e.getObj(b.dist.bars,b.def.visual_type,600,300,!0,!0))}function a(a,b){var c=[{title:g,value:b}];a.find(".fp-whisker").html(d.getObj(c,600,100));d.reposition()}function c(a,b){var c=a.def,h="";e=new viz.Histogram(!0);e.init(c.prefix,c.suffix,c.medians_string,c.high_good,c.calc_type,c.add_commas);e.field_name=c.name;d=new viz.WhiskerPlot(!0);d.init(c.prefix,c.suffix,c.medians_string,c.high_good,c.calc_type,c.add_commas);h+='<div class="fp-name">'+
c.name+"</div>";h+=c.help?'<div class="fp-help">'+c.help+"</div>":"";h+='<div class="fp-compare-to">How does the '+c.name+" of <b>"+g+"</b> compare to other "+FTB.app_name+"?</div>";return h+='<div class="fp-whisker"></div><div class="fp-histogram"></div>'}var h={},e,d,g;show_field_popup=function(d,f,e){g=e||(window.detail?detail.title:"");var n=(e=h[d])?c(e,f):"";new Box({html:'<div class="fp-wrap">'+n+"</div>",w:640,h:800,bg:"transparent"});var m=$(".fp-wrap");e&&(b(m,e),a(m,f));n||(m.spin(),$.ajax({url:"/rt?rt=ajax_field_popup_data",
dataType:"json",data:{app_id:FTB.app_id,db_name:d},success:function(e){h[d]=e;m.spin(!1).html(c(e,f));b(m,e);a(m,f)}}))};$(document).on("click",".fieldeditnumber,.fieldeditcurrency, .field-popup",function(){var a=$(this).data("field"),b=$(this).data("val");a&&show_field_popup(a,b)})})();
(function(){function b(){this.type="dist";this.width=200;this.minWidth=140}var a=inherits(b,viz.Numeric);viz.Histogram=b;a.forceInlineSuffix=!0;a.getObj=function(a,b,e,d,g,k){var f=this;e&&(f.width=e=e<f.minWidth?f.minWidth:e);f.height=d||e;var l=f.medianArray,n=parseFloat(l[0]||0),m=parseFloat(l[20]||0),s=parseFloat(l[10]||0),q=m-n,v=a.length===q+1;top_padding=50;bottom_padding=k?5:30;mini_viz_width=k?0:Math.min(0.2*d>>0,100);med_offset=(s-n)/q*e-mini_viz_width/2;graph_height=d-mini_viz_width-top_padding-
bottom_padding;maxDecimals=0;med_offset<mini_viz_width?med_offset=mini_viz_width:med_offset>e-2*mini_viz_width&&(med_offset=e-2*mini_viz_width);var p;for(d=0;d<l.length;d++)p=l[d].replace(/0*$/,"").split("."),p[1]&&p[1].length>maxDecimals&&(maxDecimals=p[1].length);l="";p=(e/a.length>>0)-1;var r,t,u,x,w=0;for(d=0;d<a.length;d++)a[d].h>w&&(w=a[d].h);for(d=0;d<a.length;d++)r=a[d].h/w*graph_height,t=d/a.length*q+n,u=a[d].x*p+d,x=graph_height-r+top_padding,l+='<div data-i="'+d+'" class="bar" style="position:absolute;top:'+
x+"px;left:"+u+"px;width:"+p+"px;height:"+r+"px;background:"+f.getColor(f.getPercent(t))+'"></div>';d='<div class="viz dist-viz"><div class="dist-tip"></div>';d+=l;k||("smart-rating"===b&&(n/=20,m/=20,s/=20),p=f.medianArray.join("|"),k=viz.display(b,n,mini_viz_width,f.prefix,f.suffix,p,f.isHighGood,f.calcType,f.addCommas)+f.longSuffix,l=viz.display(b,m,mini_viz_width,f.prefix,f.suffix,p,f.isHighGood,f.calcType,f.addCommas)+f.longSuffix,p=viz.display(b,s,mini_viz_width,f.prefix,f.suffix,p,f.isHighGood,
f.calcType,f.addCommas)+f.longSuffix,"smart-rating"===b&&(n*=20,m*=20,s*=20),d+=rectOpen(0,graph_height+top_padding+4,mini_viz_width,mini_viz_width)+"<b>Min</b>"+k+"</div>",d+=rectOpen(e-mini_viz_width,graph_height+top_padding+4,mini_viz_width,mini_viz_width)+"<b>Max</b>"+l+"</div>",d+=rectOpen(med_offset,graph_height+top_padding+4,mini_viz_width,mini_viz_width)+"<b>Median</b>"+p+"</div>");d+="</div>";f.longSuffix="";f.obj=$(f.getWrapHTML(d));if(g){var y=f.obj.find(".dist-tip");b=function(){var b=
$(this),d=b.attr("data-i")>>0,e=f.getValueString(d/a.length*q+n,24,16,!1,!1,maxDecimals),h=f.getValueString((d+1)/a.length*q+n,24,16,!1,!1,maxDecimals),g=1<a[d].h?FTB.app_plural:FTB.app_singular,k=-1!==["a","e","i","o","u"].indexOf(f.field_name[0].toLowerCase())?"an":"a",l="s"===f.field_name[f.field_name.length-1],g=l?add_commas(a[d].h)+" "+g+" "+tt(1<a[d].h?"have":"has")+" ":add_commas(a[d].h)+" "+g+" "+tt(1<a[d].h?"have":"has")+" "+tt(k)+" "+f.field_name+" ",g=v?g+(tt("of")+" "+f.getValueString(d+
n,24,16,!1,!1,maxDecimals)):g+(" between "+e+" and "+h);l&&(g+=" "+f.field_name);y.html(g).css({display:"block","border-color":b.css("background-color")})};f.obj.find(".bar").hover(b,function(){y.hide()}).on("vclick",b)}return this.obj}})();
(function(){function b(a){this.type="whisker-plot";this.width=200;this.minWidth=140;this.showLabels=!!a}var a=inherits(b,viz.Numeric);a.forceInlineSuffix=!0;viz.WhiskerPlot=b;a.getObj=function(a,b,e){b&&(this.width=b=b<this.minWidth?this.minWidth:b);this.height=e||b/2>>0;var d=this.medianArray,g,k;b="";e=d[0];var f=d[20],l=d[5],n=d[15],d=d[10],m=f-e,s=100*((d-e)/m),q=100*((l-e)/m),v=100*((n-l)/m),p=this.getColorCutoffs();k=p[0];var r=p[1],p=""+('<div class="low" style="border-color:'+this.getColor(0)+
";width:"+k+'%;"></div>'),p=p+('<div class="med" style="border-color:'+this.getColor(50)+";left:"+k+"%;width:"+r+'%;"></div>'),p=p+('<div class="high" style="border-color:'+this.getColor(100)+";width:"+(100-r-k)+'%;"></div>');"object"!==typeof a&&(a=[{value:a}]);for(r=0;r<a.length;r++){g=a[r].value;k=a[r].title||"";var t=this.getPercent(g),t=this.getColor(t),u=this.getValueString(g,15,13,t,"currency"==this.type,void 0,!0);g=100*((g-e)/m);b+='<div class="cursor" style="border-color:'+t+";"+(50>g?"left:"+
g+"%":"right:"+(100-g)+"%")+';"></div>';b+='<div class="point" style="left:'+g+'%"><span class="title" style="border-color:'+t+';">'+(k?k+"<br/>":"")+u+"</span></div>"}a='<div class="viz whisker-viz"><div class="whiskers"></div>';this.showLabels&&(a+='<label class="min">Minimum<br/>'+this.getValueString(e,15,13,"","currency"==this.type,void 0,!0)+"</label>",a+='<label class="max">Maximum<br/>'+this.getValueString(f,15,13,"","currency"==this.type,void 0,!0)+"</label>");a+='<div class="x-axis">'+p+
"</div>";l!==d&&n!=d&&(a+='<div class="box" style="left:'+q+"%;width:"+v+'%;"></div>',a+='<div class="median" style="left:'+s+'%">',a+="</div>");a+=b;a+="</div>";return this.obj=$(this.getWrapHTML(a))};a.reposition=function(){var a=this.obj,b=a.find(".title"),e=a.offset(),e=b.offset().left-e.left;0>e?b.parent().css({left:"+="+-e}):e+b.outerWidth()>a.outerWidth()&&b.parent().css({left:"-="+(e+b.outerWidth()-a.outerWidth())})}})();
